remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: HackerGPT Lite Docs
description: These docs will give you a quickstart on how to use HackerGPT Lite, an OSINT and Discovery tool that helps you learn cyber-security.
